#!/usr/bin/env python3
"""
new_application.py — Scaffold a new dated application folder.

Usage:
    python scripts/new_application.py "Acme Corp" "Senior Python Engineer"

Creates:
    applications/<YYYY-MM-DD>_<company-slug>_<role-slug>/
        jd.md           — paste the JD here
        tailored.yaml   — start from profile.yaml, trimmed and JD-tuned (Claude does this)
"""
from __future__ import annotations

import argparse
import re
import sys
from datetime import date
from pathlib import Path
from shutil import copyfile

ROOT = Path(__file__).resolve().parent.parent
PROFILE = ROOT / "source" / "profile.yaml"


def _slug(s: str) -> str:
    s = s.lower().strip()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-") or "x"


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("company")
    p.add_argument("role")
    p.add_argument("--date", default=date.today().isoformat(),
                   help="ISO date (default: today)")
    args = p.parse_args()

    slug = f"{args.date}_{_slug(args.company)}_{_slug(args.role)}"
    app_dir = ROOT / "applications" / slug
    if app_dir.exists():
        sys.exit(f"error: {app_dir} already exists.")
    app_dir.mkdir(parents=True)

    (app_dir / "jd.md").write_text(
        f"<!-- Paste the {args.company} '{args.role}' job description below.\n"
        f"     One section per heading is fine; bullet points are fine. -->\n\n"
    )

    # tailored.yaml starts as a copy of profile.yaml with a meta header pre-filled.
    profile_text = PROFILE.read_text()
    header = (
        f"# Tailored CV data for {args.company} — {args.role}\n"
        f"# Generated by scripts/new_application.py on {args.date}.\n"
        f"#\n"
        f"# Edit (or have Claude edit) this file to:\n"
        f"#   1. Pick a `headline` from basics.title_variants\n"
        f"#   2. Pick / rewrite the `summary` to mirror JD wording\n"
        f"#   3. Trim `experience` (keep most-relevant bullets, reorder, rewrite)\n"
        f"#   4. Trim `skills` (top 4–6 categories, reorder by JD relevance)\n"
        f"#   5. Trim `key_achievements` and `projects` to JD-relevant ones\n"
        f"#   6. Fill `meta.jd_keywords` with the JD's top terms (these become PDF metadata)\n"
        f"#   7. Add a `cover_letter:` section\n"
        f"#\n"
        f"meta:\n"
        f"  company: \"{args.company}\"\n"
        f"  role_title: \"{args.role}\"\n"
        f"  date_applied: {args.date}\n"
        f"  jd_keywords: []   # fill from JD — feeds PDF /Keywords metadata + score.py\n"
        f"  source_url: \"\"\n"
        f"\n"
        f"# Pick a headline string here (start with one from profile.yaml's title_variants):\n"
        f"headline: \"\"\n"
        f"\n"
        f"# Pick / rewrite a summary here (start from profile.yaml's summaries):\n"
        f"summary: \"\"\n"
        f"\n"
        f"# Below: same shape as profile.yaml — trim and edit per JD.\n"
        f"# (profile.yaml content follows; delete sections you don't want, "
        f"reorder, rewrite bullets to match JD wording.)\n"
        f"# ----------------------------------------------------------------------\n\n"
    )

    # Strip out things that don't belong in tailored.yaml verbatim
    # (title_variants and summaries — those drove the picks above; not needed in render data).
    cleaned = re.sub(r"\n\s*title_variants:[\s\S]*?(?=\n[a-z])", "\n", profile_text)
    cleaned = re.sub(r"\nsummaries:[\s\S]*?(?=\nexperience:)", "\n", cleaned)

    (app_dir / "tailored.yaml").write_text(header + cleaned)

    print(f"created {app_dir.relative_to(ROOT)}")
    print("  next steps:")
    print(f"    1. paste the JD into {app_dir.relative_to(ROOT)}/jd.md")
    print(f"    2. ask Claude to tailor {app_dir.relative_to(ROOT)}/tailored.yaml against the JD")
    print(f"    3. python scripts/render.py {app_dir.relative_to(ROOT)}/")
    print(f"    4. python scripts/score.py  {app_dir.relative_to(ROOT)}/")


if __name__ == "__main__":
    main()
